Repository SonySemiconductorSolutions/mct-model-optimization, pull requests merged in 2022-05, with the labels that each got.

#167 Added Max tensor support for KPI metric
  model_compression_toolkit/common/constants.py
  model_compression_toolkit/common/mixed_precision/kpi_aggregation_methods.py
  model_compression_toolkit/common/mixed_precision/kpi_methods.py
  model_compression_toolkit/common/mixed_precision/mixed_precision_search_facade.py
  tests/keras_tests/feature_networks_tests/feature_networks/mixed_precision_tests.py
Labels: common, size/s

#172 [Pytorch] Added new substitution, 'reshape_with_static_shapes'
  model_compression_toolkit/common/post_training_quantization.py
  model_compression_toolkit/pytorch/graph_substitutions/substitutions/reshape_with_static_shapes.py
  model_compression_toolkit/pytorch/pytorch_implementation.py
  model_compression_toolkit/pytorch/reader/graph_builders.py
  tests/pytorch_tests/model_tests/feature_models/dynamic_size_inputs_test.py
  tests/pytorch_tests/model_tests/test_feature_models_runner.py
Labels: common, pytorch, size/m

#174 [Pytorch] Updated the tests:
  tests/pytorch_tests/model_tests/base_pytorch_test.py
  tests/pytorch_tests/model_tests/feature_models/dynamic_size_inputs_test.py
  tests/pytorch_tests/model_tests/feature_models/torch_tensor_attr_net_test.py
  tests/pytorch_tests/model_tests/model_zoo_tests/base_model_test.py
  tests/pytorch_tests/model_tests/test_models_runner.py
  tests/test_suite.py
Labels: test, size/s

#182 Rename FramewrokHardwareModel to TargetPlatformCapabilities
  model_compression_toolkit/common/graph/base_graph.py
  model_compression_toolkit/common/post_training_quantization.py
  model_compression_toolkit/common/quantization/set_node_quantization_config.py
  model_compression_toolkit/common/target_platform/__init__.py
  model_compression_toolkit/common/target_platform/hardware2framework/__init__.py
  model_compression_toolkit/common/target_platform/hardware2framework/current_framework_hardware_model.py
  model_compression_toolkit/common/target_platform/hardware2framework/operations_to_layers.py
  model_compression_toolkit/common/target_platform/hardware2framework/target_platform_capabilities.py
  model_compression_toolkit/common/target_platform/hardware_model.py
  model_compression_toolkit/hardware_models/get_model.py
  model_compression_toolkit/hardware_models/keras_hardware_model/keras_default.py
  model_compression_toolkit/hardware_models/keras_hardware_model/keras_qnnpack.py
  model_compression_toolkit/hardware_models/keras_hardware_model/keras_tflite.py
  model_compression_toolkit/hardware_models/pytorch_hardware_model/pytorch_default.py
  model_compression_toolkit/hardware_models/pytorch_hardware_model/pytorch_qnnpack.py
  model_compression_toolkit/hardware_models/pytorch_hardware_model/pytorch_tflite.py
  model_compression_toolkit/keras/quantization_facade.py
  model_compression_toolkit/pytorch/quantization_facade.py
  tests/common_tests/test_hardware_model.py
  tests/keras_tests/feature_networks_tests/feature_networks/lut_quantizer.py
  tests/keras_tests/fw_hw_model_keras.py
  tests/keras_tests/test_keras_hardware_model.py
  tests/pytorch_tests/fw_hw_model_pytorch.py
  tests/pytorch_tests/test_pytorch_hardware_model.py
Labels: common, keras, pytorch, size/m

#173 KPI data API
  model_compression_toolkit/__init__.py
  model_compression_toolkit/common/graph/base_graph.py
  model_compression_toolkit/common/mixed_precision/kpi_aggregation_methods.py
  model_compression_toolkit/common/mixed_precision/kpi_data.py
  model_compression_toolkit/common/mixed_precision/mixed_precision_search_manager.py
  model_compression_toolkit/common/post_training_quantization.py
  model_compression_toolkit/keras/kpi_data_facade.py
  model_compression_toolkit/pytorch/kpi_data_facade.py
  tests/keras_tests/function_tests/test_kpi_data.py
  tests/pytorch_tests/function_tests/kpi_data_test.py
  tests/pytorch_tests/function_tests/test_function_runner.py
Labels: common, keras, pytorch, size/l

#184 Rename HW2FW to TP2FW
  model_compression_toolkit/common/graph/base_graph.py
  model_compression_toolkit/common/post_training_quantization.py
  model_compression_toolkit/common/quantization/set_node_quantization_config.py
  model_compression_toolkit/common/target_platform/__init__.py
  model_compression_toolkit/common/target_platform/targetplatform2framework/__init__.py
  model_compression_toolkit/common/target_platform/targetplatform2framework/attribute_filter.py
  model_compression_toolkit/common/target_platform/targetplatform2framework/current_framework_hardware_model.py
  model_compression_toolkit/common/target_platform/targetplatform2framework/framework_hardware_model_component.py
  model_compression_toolkit/common/target_platform/targetplatform2framework/layer_filter_params.py
  model_compression_toolkit/common/target_platform/targetplatform2framework/operations_to_layers.py
  model_compression_toolkit/common/target_platform/targetplatform2framework/target_platform_capabilities.py
  model_compression_toolkit/hardware_models/keras_hardware_model/keras_qnnpack.py
  model_compression_toolkit/hardware_models/keras_hardware_model/keras_tflite.py
  model_compression_toolkit/hardware_models/pytorch_hardware_model/pytorch_default.py
  model_compression_toolkit/hardware_models/pytorch_hardware_model/pytorch_qnnpack.py
  model_compression_toolkit/hardware_models/pytorch_hardware_model/pytorch_tflite.py
  model_compression_toolkit/keras/quantization_facade.py
  tests/keras_tests/test_keras_hardware_model.py
  tests/pytorch_tests/fw_hw_model_pytorch.py
  tests/pytorch_tests/test_pytorch_hardware_model.py
Labels: common, keras, size/s

#185 Rename HardwareModel to TargetPlatformModel
  model_compression_toolkit/common/target_platform/__init__.py
  model_compression_toolkit/common/target_platform/current_hardware_model.py
  model_compression_toolkit/common/target_platform/hardware_model_component.py
  model_compression_toolkit/common/target_platform/operators.py
  model_compression_toolkit/common/target_platform/target_platform_model.py
  model_compression_toolkit/common/target_platform/targetplatform2framework/target_platform_capabilities.py
  model_compression_toolkit/hardware_models/default_hwm.py
  model_compression_toolkit/hardware_models/keras_hardware_model/keras_default.py
  model_compression_toolkit/hardware_models/pytorch_hardware_model/pytorch_default.py
  model_compression_toolkit/hardware_models/qnnpack.py
  model_compression_toolkit/hardware_models/tflite.py
  tests/common_tests/helpers/activation_mp_hw_model.py
  tests/common_tests/test_hardware_model.py
  tests/keras_tests/feature_networks_tests/feature_networks/lut_quantizer.py
  tests/keras_tests/test_keras_hardware_model.py
  tests/pytorch_tests/test_pytorch_hardware_model.py
  tutorials/example_keras_mobilenet.py
  tutorials/example_keras_mobilenet_mixed_precision.py
  tutorials/example_pytorch_mobilenet_v2.py
Labels: size/m

#186 Rename hw_models to tpc_models
  model_compression_toolkit/__init__.py
  model_compression_toolkit/tpc_models/__init__.py
  model_compression_toolkit/tpc_models/default_hwm.py
  model_compression_toolkit/tpc_models/get_model.py
  model_compression_toolkit/tpc_models/keras_hardware_model/__init__.py
  model_compression_toolkit/tpc_models/keras_hardware_model/keras_default.py
  model_compression_toolkit/tpc_models/keras_hardware_model/keras_qnnpack.py
  model_compression_toolkit/tpc_models/keras_hardware_model/keras_tflite.py
  model_compression_toolkit/tpc_models/pytorch_hardware_model/__init__.py
  model_compression_toolkit/tpc_models/pytorch_hardware_model/pytorch_default.py
  model_compression_toolkit/tpc_models/pytorch_hardware_model/pytorch_qnnpack.py
  model_compression_toolkit/tpc_models/pytorch_hardware_model/pytorch_tflite.py
  model_compression_toolkit/tpc_models/qnnpack.py
  model_compression_toolkit/tpc_models/tflite.py
  tests/common_tests/helpers/generate_test_hw_model.py
  tests/common_tests/test_hardware_model.py
  tests/keras_tests/feature_networks_tests/feature_networks/bn_folding_test.py
  tests/keras_tests/feature_networks_tests/feature_networks/gptq_test.py
  tests/keras_tests/feature_networks_tests/feature_networks/input_scaling_test.py
  tests/keras_tests/feature_networks_tests/feature_networks/multi_inputs_to_node_test.py
  tests/keras_tests/feature_networks_tests/feature_networks/multiple_inputs_node_tests.py
  tests/keras_tests/feature_networks_tests/feature_networks/reused_layer_mixed_precision_test.py
  tests/keras_tests/feature_networks_tests/feature_networks/shift_neg_activation_test.py
  tests/keras_tests/feature_networks_tests/feature_networks/split_conv_bug_test.py
  tests/keras_tests/feature_networks_tests/feature_networks/symmetric_threshold_selection_activation_test.py
  tests/keras_tests/feature_networks_tests/feature_networks/test_kmeans_quantizer.py
  tests/keras_tests/feature_networks_tests/feature_networks/uniform_range_selection_activation_test.py
  tests/keras_tests/feature_networks_tests/feature_networks/weights_mixed_precision_tests.py
  tests/keras_tests/feature_networks_tests/test_networks_runner.py
  tests/keras_tests/function_tests/test_kl_error_quantization_configurations.py
  tests/keras_tests/function_tests/test_lp_search_bitwidth.py
  tests/keras_tests/function_tests/test_quantization_configurations.py
  tests/keras_tests/function_tests/test_symmetric_threshold_selection_weights.py
  tests/keras_tests/function_tests/test_uniform_range_selection_weights.py
  tests/keras_tests/fw_hw_model_keras.py
  tests/keras_tests/layer_tests/base_keras_layer_test.py
  tests/pytorch_tests/function_tests/kpi_data_test.py
  tests/pytorch_tests/fw_hw_model_pytorch.py
  tests/pytorch_tests/layer_tests/base_pytorch_layer_test.py
  tests/pytorch_tests/model_tests/base_pytorch_test.py
  tests/pytorch_tests/model_tests/feature_models/mixed_precision_test.py
  tests/pytorch_tests/model_tests/feature_models/relu_bound_test.py
  tests/pytorch_tests/model_tests/feature_models/scale_equalization_test.py
  tests/pytorch_tests/model_tests/feature_models/shift_negative_activation_test.py
  tests/pytorch_tests/model_tests/feature_models/test_softmax_shift.py
Labels: size/m

#189 Rename FwHwModelComponent to TPCComponent
  model_compression_toolkit/common/target_platform/targetplatform2framework/operations_to_layers.py
  model_compression_toolkit/common/target_platform/targetplatform2framework/target_platform_capabilities.py
  model_compression_toolkit/common/target_platform/targetplatform2framework/target_platform_capabilities_component.py
Labels: size/s

#197 Rename CurrentFrameworkHardwareModel to CurrentTPC
  model_compression_toolkit/common/target_platform/__init__.py
  model_compression_toolkit/common/target_platform/targetplatform2framework/__init__.py
  model_compression_toolkit/common/target_platform/targetplatform2framework/current_tpc.py
  model_compression_toolkit/common/target_platform/targetplatform2framework/operations_to_layers.py
  model_compression_toolkit/common/target_platform/targetplatform2framework/target_platform_capabilities.py
  model_compression_toolkit/common/target_platform/targetplatform2framework/target_platform_capabilities_component.py
Labels: size/s

#198 Rename get_default_keras_model function to get_default_tp_model
  model_compression_toolkit/tpc_models/default_hwm.py
  model_compression_toolkit/tpc_models/keras_hardware_model/keras_default.py
  model_compression_toolkit/tpc_models/pytorch_hardware_model/pytorch_default.py
  tests/common_tests/test_hardware_model.py
  tests/keras_tests/layer_tests/base_keras_layer_test.py
  tests/pytorch_tests/layer_tests/base_pytorch_layer_test.py
  tests/pytorch_tests/model_tests/feature_models/mixed_precision_test.py
  tests/pytorch_tests/model_tests/feature_models/relu_bound_test.py
  tests/pytorch_tests/model_tests/feature_models/scale_equalization_test.py
  tests/pytorch_tests/model_tests/feature_models/shift_negative_activation_test.py
  tests/pytorch_tests/model_tests/feature_models/test_softmax_shift.py
Labels: size/s

#199 Rename get_keras_hw_model_tflite
  model_compression_toolkit/tpc_models/get_model.py
  model_compression_toolkit/tpc_models/keras_hardware_model/keras_tflite.py
Labels: size/xs

#200 Rename keras_hardware_model pkg to keras_tp_models
  model_compression_toolkit/tpc_models/get_model.py
  model_compression_toolkit/tpc_models/keras_tp_models/__init__.py
  model_compression_toolkit/tpc_models/keras_tp_models/keras_default.py
  model_compression_toolkit/tpc_models/keras_tp_models/keras_qnnpack.py
  model_compression_toolkit/tpc_models/keras_tp_models/keras_tflite.py
  tests/common_tests/helpers/generate_test_hw_model.py
  tests/keras_tests/feature_networks_tests/feature_networks/bn_folding_test.py
  tests/keras_tests/feature_networks_tests/feature_networks/gptq_test.py
  tests/keras_tests/feature_networks_tests/feature_networks/input_scaling_test.py
  tests/keras_tests/feature_networks_tests/feature_networks/multi_inputs_to_node_test.py
  tests/keras_tests/feature_networks_tests/feature_networks/multiple_inputs_node_tests.py
  tests/keras_tests/feature_networks_tests/feature_networks/reused_layer_mixed_precision_test.py
  tests/keras_tests/feature_networks_tests/feature_networks/shift_neg_activation_test.py
  tests/keras_tests/feature_networks_tests/feature_networks/split_conv_bug_test.py
  tests/keras_tests/feature_networks_tests/feature_networks/symmetric_threshold_selection_activation_test.py
  tests/keras_tests/feature_networks_tests/feature_networks/test_kmeans_quantizer.py
  tests/keras_tests/feature_networks_tests/feature_networks/uniform_range_selection_activation_test.py
  tests/keras_tests/feature_networks_tests/feature_networks/weights_mixed_precision_tests.py
  tests/keras_tests/feature_networks_tests/test_networks_runner.py
  tests/keras_tests/function_tests/test_kl_error_quantization_configurations.py
  tests/keras_tests/function_tests/test_lp_search_bitwidth.py
  tests/keras_tests/function_tests/test_quantization_configurations.py
  tests/keras_tests/function_tests/test_symmetric_threshold_selection_weights.py
  tests/keras_tests/function_tests/test_uniform_range_selection_weights.py
  tests/keras_tests/fw_hw_model_keras.py
  tests/keras_tests/layer_tests/base_keras_layer_test.py
Labels: size/s

#175 Activation mixed precision PyTorch support
  model_compression_toolkit/common/graph/base_node.py
  model_compression_toolkit/pytorch/back2framework/model_builder.py
  model_compression_toolkit/pytorch/mixed_precision/mixed_precision_wrapper.py
  model_compression_toolkit/pytorch/mixed_precision/sensitivity_evaluation.py
  tests/common_tests/helpers/generate_test_tp_model.py
  tests/pytorch_tests/model_tests/feature_models/mixed_precision_activation_test.py
  tests/pytorch_tests/model_tests/feature_models/mixed_precision_weights_test.py
  tests/pytorch_tests/model_tests/test_feature_models_runner.py
  tests/pytorch_tests/tpc_pytorch.py
Labels: size/m

#203 Add TF argmax layer to default TPC
  model_compression_toolkit/tpc_models/keras_tp_models/keras_default.py
  tests/keras_tests/tpc_keras.py
Labels: size/xs

#204 Remove timeout in nightly TF testssuite
  .github/workflows/run_tests_suite_tf25.yml
  .github/workflows/run_tests_suite_tf26.yml
  .github/workflows/run_tests_suite_tf27.yml
Labels: size/xs

#205 minor fix in assertion in pytorch mp wrapper
  model_compression_toolkit/pytorch/mixed_precision/mixed_precision_wrapper.py
Labels: size/xs

#206 added layers types for keras default tpc NoQuantization list
  model_compression_toolkit/tpc_models/keras_tp_models/keras_default.py
  tests/keras_tests/tpc_keras.py
Labels: size/s

#208 minor fix in output size computation
  model_compression_toolkit/common/graph/base_node.py
  tests/keras_tests/function_tests/test_kpi_data.py
  tests/pytorch_tests/function_tests/kpi_data_test.py
Labels: size/xs

#210 fix issue in model builder for mixed precision
  model_compression_toolkit/keras/back2framework/model_builder.py
Labels: size/s

#217 Mixed-precision tutorial update
  model_compression_toolkit/keras/kpi_data_facade.py
  model_compression_toolkit/pytorch/kpi_data_facade.py
  tutorials/example_keras_mobilenet_mixed_precision.py
Labels: keras, pytorch, size/s

#220 Added tutorial for pytorch mixed-precision
  tutorials/example_pytorch_mobilenet_mixed_precision.py
Labels: size/m

#221 Release fixes
  docsrc/source/api/api_docs/index.rst
  docsrc/source/api/api_docs/methods/get_model.rst
  docsrc/source/api/api_docs/methods/get_target_platform_capabilities.rst
  docsrc/source/api/api_docs/methods/keras_kpi_data.rst
  docsrc/source/api/api_docs/methods/pytorch_kpi_data.rst
  docsrc/source/api/api_docs/modules/layer_filters.rst
  docsrc/source/api/api_docs/modules/network_editor.rst
  docsrc/source/api/api_docs/modules/target_platform.rst
  docsrc/source/api/api_docs/notes/hwm_note.rst
  docsrc/source/api/api_docs/notes/tpc_note.rst
  docsrc/source/guidelines/quickstart_keras.rst
  docsrc/source/guidelines/quickstart_pytorch.rst
  docsrc/source/index.rst
  model_compression_toolkit/common/quantization/quantization_config.py
  model_compression_toolkit/keras/kpi_data_facade.py
  model_compression_toolkit/keras/quantization_facade.py
  model_compression_toolkit/pytorch/kpi_data_facade.py
  model_compression_toolkit/pytorch/quantization_facade.py
  tutorials/example_keras_mobilenet.py
  tutorials/example_pytorch_mobilenet_v2.py
Labels: keras, pytorch, size/m

#225 Fix issue 223
  .github/ISSUE_TEMPLATE/mct_issue_template.yaml
  model_compression_toolkit/tpc_models/get_target_platform_capabilities.py
Labels: size/s

#215 Remove reused nodes from activation configurable nodes list
  model_compression_toolkit/common/graph/base_graph.py
Labels: size/xs

#216 Minor fix in BaseNode get_weights_by_keys method
  model_compression_toolkit/common/graph/base_node.py
Labels: size/xs

#207 fix issues with pytorch mp wrapper and model builder
  model_compression_toolkit/pytorch/back2framework/model_builder.py
  model_compression_toolkit/pytorch/mixed_precision/mixed_precision_wrapper.py
  model_compression_toolkit/pytorch/mixed_precision/sensitivity_evaluation.py
  tests/pytorch_tests/model_tests/feature_models/mixed_precision_activation_test.py
  tests/pytorch_tests/model_tests/test_feature_models_runner.py
Labels: size/s

#224 Throwing exception when trying to quantize activation tensor of unsupported dtype
  model_compression_toolkit/keras/back2framework/model_builder.py
  model_compression_toolkit/keras/quantizer/fake_quant_builder.py
Labels: size/xs

#228 Api change
  model_compression_toolkit/__init__.py
  model_compression_toolkit/common/framework_implementation.py
  model_compression_toolkit/common/mixed_precision/bit_width_setter.py
  model_compression_toolkit/common/mixed_precision/kpi.py
  model_compression_toolkit/common/mixed_precision/kpi_data.py
  model_compression_toolkit/common/mixed_precision/mixed_precision_quantization_config.py
  model_compression_toolkit/common/mixed_precision/mixed_precision_search_facade.py
  model_compression_toolkit/common/mixed_precision/mixed_precision_search_manager.py
  model_compression_toolkit/common/network_editors/edit_network.py
  model_compression_toolkit/common/post_training_quantization.py
  model_compression_toolkit/common/quantization/core_config.py
  model_compression_toolkit/common/quantization/debug_config.py
  model_compression_toolkit/common/quantization/quantization_config.py
  model_compression_toolkit/common/quantization/set_node_quantization_config.py
  model_compression_toolkit/common/substitutions/shift_negative_activation.py
  model_compression_toolkit/common/target_platform/op_quantization_config.py
  model_compression_toolkit/keras/graph_substitutions/substitutions/multi_head_attention_decomposition.py
  model_compression_toolkit/keras/graph_substitutions/substitutions/shift_negative_activation.py
  model_compression_toolkit/keras/keras_implementation.py
  model_compression_toolkit/keras/kpi_data_facade.py
  model_compression_toolkit/keras/quantization_facade.py
  model_compression_toolkit/pytorch/graph_substitutions/substitutions/shift_negative_activation.py
  model_compression_toolkit/pytorch/kpi_data_facade.py
  model_compression_toolkit/pytorch/pytorch_implementation.py
  model_compression_toolkit/pytorch/quantization_facade.py
  model_compression_toolkit/tpc_models/keras_tp_models/keras_default.py
  tests/keras_tests/function_tests/test_lp_search_bitwidth.py
  tests/keras_tests/function_tests/test_symmetric_threshold_selection_weights.py
  tests/keras_tests/function_tests/test_uniform_range_selection_weights.py
Labels: common, keras, pytorch, size/l

#230 fix api_change PR
  model_compression_toolkit/keras/quantization_facade.py
  model_compression_toolkit/pytorch/quantization_facade.py
Labels: keras, pytorch, size/xs

#211 Add linear collapsing for Conv2D
  model_compression_toolkit/common/framework_implementation.py
  model_compression_toolkit/common/post_training_quantization.py
  model_compression_toolkit/common/quantization/quantization_config.py
  model_compression_toolkit/common/substitutions/linear_collapsing.py
  model_compression_toolkit/common/substitutions/linear_collapsing_substitution.py
  model_compression_toolkit/keras/constants.py
  model_compression_toolkit/keras/graph_substitutions/substitutions/linear_collapsing.py
  model_compression_toolkit/keras/keras_implementation.py
  model_compression_toolkit/pytorch/constants.py
  model_compression_toolkit/pytorch/graph_substitutions/substitutions/linear_collapsing.py
  model_compression_toolkit/pytorch/pytorch_implementation.py
  tests/keras_tests/feature_networks_tests/feature_networks/linear_collapsing_test.py
  tests/keras_tests/feature_networks_tests/test_features_runner.py
  tests/pytorch_tests/model_tests/base_pytorch_feature_test.py
  tests/pytorch_tests/model_tests/feature_models/layer_name_test.py
  tests/pytorch_tests/model_tests/feature_models/linear_collapsing_test.py
  tests/pytorch_tests/model_tests/feature_models/output_in_the_middle_test.py
  tests/pytorch_tests/model_tests/feature_models/relu_bound_test.py
  tests/pytorch_tests/model_tests/feature_models/reuse_layer_net_test.py
  tests/pytorch_tests/model_tests/test_feature_models_runner.py
Labels: common, keras, pytorch, size/l

#237 Fix linear collapsing issues
  model_compression_toolkit/pytorch/graph_substitutions/substitutions/linear_collapsing.py
  tests/pytorch_tests/model_tests/feature_models/linear_collapsing_test.py
Labels: size/xs

#239 Fix failed candidates filter test due to config changes
  tests/keras_tests/function_tests/test_cfg_candidates_filter.py
Labels: size/xs

#209 Mixed precision metric interest points bound
  model_compression_toolkit/common/mixed_precision/mixed_precision_quantization_config.py
  model_compression_toolkit/common/mixed_precision/sensitivity_evaluation_manager.py
  tests/keras_tests/function_tests/test_sensitivity_metric_interest_points.py
Labels: size/m

#227 Compute mixed-precision metric for best config only once
  model_compression_toolkit/common/graph/base_graph.py
  model_compression_toolkit/common/mixed_precision/mixed_precision_search_manager.py
  model_compression_toolkit/common/mixed_precision/search_methods/linear_programming.py
  tests/keras_tests/function_tests/test_lp_search_bitwidth.py
Labels: size/s

#235 Add license to core_config.py & debug_config.py
  model_compression_toolkit/common/quantization/core_config.py
  model_compression_toolkit/common/quantization/debug_config.py
Labels: size/s

#229 move keras Reshape attribute "target_shape" to constants.py
  model_compression_toolkit/keras/constants.py
  model_compression_toolkit/keras/graph_substitutions/substitutions/multi_head_attention_decomposition.py
Labels: keras, size/s

#232 Add tf.compat.v1.shape to keras_default TPC no quantization list
  model_compression_toolkit/tpc_models/keras_tp_models/keras_default.py
Labels: size/xs

#233 TF mixed-precision validate max config
  model_compression_toolkit/keras/quantizer/mixed_precision/quantization_config_factory.py
  model_compression_toolkit/keras/quantizer/mixed_precision/selective_activation_quantizer.py
  model_compression_toolkit/keras/quantizer/mixed_precision/selective_quantize_config.py
  model_compression_toolkit/keras/quantizer/mixed_precision/selective_weights_quantizer.py
Labels: size/s

#242 Fix issue with MP interest-point filtering test
  tests/keras_tests/function_tests/test_sensitivity_metric_interest_points.py
  tests/test_suite.py
Labels: test, size/xs

#238 Add residual collapsing of Conv2D
  model_compression_toolkit/common/framework_implementation.py
  model_compression_toolkit/common/post_training_quantization.py
  model_compression_toolkit/common/quantization/quantization_config.py
  model_compression_toolkit/common/substitutions/linear_collapsing_substitution.py
  model_compression_toolkit/common/substitutions/residual_collapsing.py
  model_compression_toolkit/keras/graph_substitutions/substitutions/residual_collapsing.py
  model_compression_toolkit/keras/keras_implementation.py
  model_compression_toolkit/pytorch/graph_substitutions/substitutions/residual_collapsing.py
  model_compression_toolkit/pytorch/pytorch_implementation.py
  tests/keras_tests/feature_networks_tests/feature_networks/residual_collapsing_test.py
  tests/keras_tests/feature_networks_tests/test_features_runner.py
  tests/pytorch_tests/model_tests/feature_models/residual_collapsing_test.py
  tests/pytorch_tests/model_tests/test_feature_models_runner.py
Labels: common, keras, pytorch, size/l

#246 Add Technical Constrains to docs
  docsrc/source/index.rst
Labels: size/xs

#241 Mixed-precision result visualizer
  docsrc/images/mp_bitwidth_config.png
  docsrc/source/guidelines/visualization.rst
  model_compression_toolkit/common/graph/base_graph.py
  model_compression_toolkit/common/post_training_quantization.py
  model_compression_toolkit/common/visualization/final_config_visualizer.py
Labels: common, size/m

#243 remove duplicate arguments from post_training_quantization
  model_compression_toolkit/common/post_training_quantization.py
  model_compression_toolkit/keras/quantization_facade.py
  model_compression_toolkit/pytorch/quantization_facade.py
Labels: common, keras, pytorch, size/s

#245 Total KPI metric
  model_compression_toolkit/common/mixed_precision/kpi.py
  model_compression_toolkit/common/mixed_precision/kpi_aggregation_methods.py
  model_compression_toolkit/common/mixed_precision/kpi_data.py
  model_compression_toolkit/common/mixed_precision/kpi_methods.py
  model_compression_toolkit/common/mixed_precision/mixed_precision_search_facade.py
  model_compression_toolkit/common/mixed_precision/mixed_precision_search_manager.py
  model_compression_toolkit/common/mixed_precision/search_methods/linear_programming.py
  model_compression_toolkit/keras/kpi_data_facade.py
  model_compression_toolkit/pytorch/kpi_data_facade.py
  tests/keras_tests/feature_networks_tests/feature_networks/mixed_precision_tests.py
  tests/keras_tests/feature_networks_tests/test_features_runner.py
Labels: keras, pytorch, size/m

#236 Fusion implementation using Target Platform configuration
  model_compression_toolkit/common/framework_implementation.py
  model_compression_toolkit/common/fusion/__init__.py
  model_compression_toolkit/common/fusion/layer_fusing.py
  model_compression_toolkit/common/mixed_precision/kpi_data.py
  model_compression_toolkit/common/post_training_quantization.py
  model_compression_toolkit/common/user_info.py
  model_compression_toolkit/keras/graph_substitutions/substitutions/mark_activation.py
  model_compression_toolkit/keras/keras_implementation.py
  model_compression_toolkit/pytorch/graph_substitutions/substitutions/mark_activation.py
  model_compression_toolkit/pytorch/pytorch_implementation.py
  tests/keras_tests/feature_networks_tests/feature_networks/activation_relu_bound_to_power_of_2_test.py
  tests/keras_tests/feature_networks_tests/feature_networks/layer_fusing_test.py
  tests/keras_tests/feature_networks_tests/feature_networks/mark_activation_test.py
  tests/keras_tests/feature_networks_tests/feature_networks/mixed_precision_tests.py
  tests/keras_tests/feature_networks_tests/feature_networks/nested_networks/nested_model_multiple_inputs_test.py
  tests/keras_tests/feature_networks_tests/test_features_runner.py
  tests/pytorch_tests/model_tests/feature_models/layer_fusing_test.py
  tests/pytorch_tests/model_tests/feature_models/mixed_precision_activation_test.py
  tests/pytorch_tests/model_tests/test_feature_models_runner.py
Labels: common, keras, pytorch, size/l

#244 Add MultiHeadAttention Layer decomposition for PyTorch
  model_compression_toolkit/pytorch/constants.py
  model_compression_toolkit/pytorch/graph_substitutions/substitutions/multi_head_attention_decomposition.py
  model_compression_toolkit/pytorch/pytorch_implementation.py
  tests/pytorch_tests/model_tests/base_pytorch_test.py
  tests/pytorch_tests/model_tests/feature_models/multi_head_attention_test.py
  tests/pytorch_tests/model_tests/test_feature_models_runner.py
Labels: pytorch, size/l

#252 Change protobuf to previous version
  requirements.txt
Labels: size/xs

#249 Add new fusions to default TPC and fix issue in fusion algorithm
  model_compression_toolkit/common/fusion/layer_fusing.py
  model_compression_toolkit/common/target_platform/targetplatform2framework/operations_to_layers.py
  model_compression_toolkit/tpc_models/default_tp_model.py
  model_compression_toolkit/tpc_models/keras_tp_models/keras_default.py
  model_compression_toolkit/tpc_models/pytorch_tp_models/pytorch_default.py
  tests/keras_tests/feature_networks_tests/feature_networks/nested_networks/nested_model_multiple_inputs_test.py
Labels: size/s

#251 Fix issue: Editing error method has no effect
  model_compression_toolkit/common/quantization/node_quantization_config.py
  tests/keras_tests/feature_networks_tests/feature_networks/network_editor/edit_error_method_test.py
  tests/keras_tests/feature_networks_tests/test_features_runner.py
Labels: size/m

#253 fix fusion test
  tests/keras_tests/function_tests/test_cfg_candidates_filter.py
Labels: size/xs

#256 Fix experimental API docs
  docsrc/source/api/api_docs/index.rst
  docsrc/source/api/experimental_api_docs/index.rst
  model_compression_toolkit/common/quantization/core_config.py
  model_compression_toolkit/keras/kpi_data_facade.py
  model_compression_toolkit/keras/quantization_facade.py
  model_compression_toolkit/pytorch/quantization_facade.py
Labels: keras, pytorch, size/s

#254 Fix Bug in MHA Pytorch
  model_compression_toolkit/pytorch/graph_substitutions/substitutions/multi_head_attention_decomposition.py
Labels: size/xs

#248 fix sensitivity evaluation to change mp model back to baseline config
  model_compression_toolkit/common/mixed_precision/search_methods/linear_programming.py
  model_compression_toolkit/keras/mixed_precision/sensitivity_evaluation.py
  model_compression_toolkit/pytorch/mixed_precision/sensitivity_evaluation.py
  tests/keras_tests/function_tests/test_lp_search_bitwidth.py
Labels: size/s

#247 Fix issue: network editor doesnt affect final configs
  model_compression_toolkit/common/mixed_precision/bit_width_setter.py
  model_compression_toolkit/common/network_editors/edit_network.py
  model_compression_toolkit/common/post_training_quantization.py
  tests/keras_tests/feature_networks_tests/feature_networks/network_editor/change_qc_attr_test.py
  tests/keras_tests/feature_networks_tests/test_features_runner.py
  tests/keras_tests/function_tests/test_symmetric_threshold_selection_weights.py
  tests/keras_tests/function_tests/test_uniform_range_selection_weights.py
Labels: common, size/m
