Repository SonySemiconductorSolutions/mct-model-optimization, pull requests merged in 2022-07, with the labels that each got.

#283 split post_training_quantization.py blocks
  model_compression_toolkit/core/analyzer.py
  model_compression_toolkit/core/common/bias_correction/apply_bias_correction_to_graph.py
  model_compression_toolkit/core/common/mixed_precision/kpi_data.py
  model_compression_toolkit/core/common/visualization/nn_visualizer.py
  model_compression_toolkit/core/exporter.py
  model_compression_toolkit/core/keras/quantization_facade.py
  model_compression_toolkit/core/pytorch/quantization_facade.py
  model_compression_toolkit/core/runner.py
  model_compression_toolkit/gptq/keras/quantization_facade.py
  model_compression_toolkit/gptq/pytorch/quantization_facade.py
  model_compression_toolkit/gptq/runner.py
  model_compression_toolkit/ptq/keras/quantization_facade.py
  model_compression_toolkit/ptq/pytorch/quantization_facade.py
  model_compression_toolkit/ptq/runner.py
  tests/keras_tests/function_tests/test_symmetric_threshold_selection_weights.py
  tests/keras_tests/function_tests/test_uniform_range_selection_weights.py
Labels: keras, pytorch, size/l

#284 Fix irrelevant TPC logs
  model_compression_toolkit/core/tpc_models/default_tpc/v2/tp_model.py
  model_compression_toolkit/core/tpc_models/default_tpc/v2/tpc_pytorch.py
  model_compression_toolkit/core/tpc_models/default_tpc/v3/tp_model.py
  model_compression_toolkit/core/tpc_models/default_tpc/v3/tpc_pytorch.py
  model_compression_toolkit/core/tpc_models/tflite_tpc/v1/tp_model.py
  model_compression_toolkit/core/tpc_models/tflite_tpc/v1/tpc_keras.py
Labels: size/s

#285 Fix documentation
  docsrc/source/api/api_docs/index.rst
  docsrc/source/api/experimental_api_docs/classes/FolderImageLoader.rst
  docsrc/source/api/experimental_api_docs/modules/target_platform.rst
  docsrc/source/api/experimental_api_docs/notes/tpc_note.rst
  docsrc/source/conf.py
  model_compression_toolkit/core/keras/kpi_data_facade.py
  model_compression_toolkit/core/keras/quantization_facade.py
  model_compression_toolkit/core/pytorch/quantization_facade.py
  model_compression_toolkit/gptq/keras/quantization_facade.py
Labels: keras, pytorch, size/s

#289 Add Gumbel rounding
  model_compression_toolkit/__init__.py
  model_compression_toolkit/core/keras/quantizer/base_quantizer.py
  model_compression_toolkit/gptq/common/gptq_config.py
  model_compression_toolkit/gptq/common/gptq_constants.py
  model_compression_toolkit/gptq/keras/gptq_training.py
  model_compression_toolkit/gptq/keras/graph_info.py
  model_compression_toolkit/gptq/keras/optimizers/__init__.py
  model_compression_toolkit/gptq/keras/optimizers/sam_optimizer.py
  model_compression_toolkit/gptq/keras/quantization_facade.py
  model_compression_toolkit/gptq/keras/quantizer/config_factory.py
  model_compression_toolkit/gptq/keras/quantizer/configs/__init__.py
  model_compression_toolkit/gptq/keras/quantizer/configs/base_quantizer_gptq_config.py
  model_compression_toolkit/gptq/keras/quantizer/configs/weight_quantizer_gptq_config.py
  model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/__init__.py
  model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/base_gumbel_rounding.py
  model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/gumbel_softmax.py
  model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/symmetric_gumbel.py
  model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/uniform_gumbel.py
  model_compression_toolkit/gptq/keras/quantizer/kernel_functions.py
  model_compression_toolkit/gptq/keras/quantizer/quant_utils.py
  model_compression_toolkit/gptq/keras/quantizer/ste_rounding/__init__.py
  model_compression_toolkit/gptq/keras/quantizer/ste_rounding/symmetric_ste.py
  model_compression_toolkit/gptq/keras/quantizer/utils.py
  model_compression_toolkit/gptq/keras/quantizer/weight_quantizer_gptq_config.py
  tests/keras_tests/feature_networks_tests/feature_networks/gptq_test.py
  tests/keras_tests/function_tests/test_get_gptq_config.py
Labels: size/xl

#287 PyTorch support for gradient-based weights for mixed-precision metric
  model_compression_toolkit/core/common/framework_implementation.py
  model_compression_toolkit/core/keras/back2framework/model_gradients.py
  model_compression_toolkit/core/keras/keras_implementation.py
  model_compression_toolkit/core/pytorch/back2framework/model_gradients.py
  model_compression_toolkit/core/pytorch/pytorch_implementation.py
  tests/keras_tests/function_tests/test_model_gradients.py
  tests/pytorch_tests/function_tests/model_gradients_test.py
  tests/pytorch_tests/function_tests/test_function_runner.py
Labels: common, keras, pytorch, size/l

#292 Revert small change from previous update, allowing 8bit LUT weights quantization
  model_compression_toolkit/core/common/quantization/quantization_params_generation/lut_kmeans_params.py
Labels: size/xs

#291 Pytorch Activation LUT Kmean Quantizer
  model_compression_toolkit/core/pytorch/default_framework_info.py
  model_compression_toolkit/core/pytorch/quantizer/lut_fake_quant.py
  tests/pytorch_tests/model_tests/feature_models/lut_quantizer_test.py
  tests/pytorch_tests/model_tests/test_feature_models_runner.py
Labels: pytorch, size/m

#293 Minor fix in Pytorch LUT test (remove unnecessary import)
  tests/pytorch_tests/model_tests/feature_models/lut_quantizer_test.py
Labels: size/xs

#294 fix shape in MHA decomposition substitution
  model_compression_toolkit/core/keras/graph_substitutions/substitutions/multi_head_attention_decomposition.py
Labels: size/xs

#295 Add TPC README
  docsrc/images/tpc.jpg
  docsrc/source/api/experimental_api_docs/modules/target_platform.rst
  model_compression_toolkit/core/tpc_models/README.md
Labels: size/s

#296 adjust MHA substitution to supported nodes and attributes
  model_compression_toolkit/core/keras/constants.py
  model_compression_toolkit/core/keras/graph_substitutions/substitutions/multi_head_attention_decomposition.py
Labels: keras, size/s

#297 MHA substitution: use Reshape instead of Stack to collect iterations
  model_compression_toolkit/core/keras/graph_substitutions/substitutions/multi_head_attention_decomposition.py
Labels: size/s

#298 Mixed-Precision LUT TPC
  model_compression_toolkit/core/tpc_models/default_tpc/target_platform_capabilities.py
  model_compression_toolkit/core/tpc_models/default_tpc/v3_lut/__init__.py
  model_compression_toolkit/core/tpc_models/default_tpc/v3_lut/tp_model.py
  model_compression_toolkit/core/tpc_models/default_tpc/v3_lut/tpc_keras.py
  model_compression_toolkit/core/tpc_models/default_tpc/v3_lut/tpc_pytorch.py
Labels: size/m

#299 Add substitution: LayerNorm --> LayerNorm+BatchNorm
  model_compression_toolkit/core/keras/constants.py
  model_compression_toolkit/core/keras/graph_substitutions/substitutions/layer_norm_decomposition.py
  model_compression_toolkit/core/keras/keras_implementation.py
  tests/keras_tests/feature_networks_tests/feature_networks/layer_norm_substitution_test.py
  tests/keras_tests/feature_networks_tests/test_features_runner.py
Labels: keras, size/m

#307 Remove bias separate training loop
  model_compression_toolkit/gptq/keras/gptq_training.py
  model_compression_toolkit/gptq/keras/optimizers/sam_optimizer.py
  model_compression_toolkit/gptq/keras/quantizer/gumbel_rounding/gumbel_softmax.py
  tests/keras_tests/feature_networks_tests/feature_networks/gptq_test.py
Labels: size/m

#309 Creating a package for all common KPI-related files and functions
  model_compression_toolkit/__init__.py
  model_compression_toolkit/core/common/mixed_precision/kpi_tools/__init__.py
  model_compression_toolkit/core/common/mixed_precision/kpi_tools/kpi.py
  model_compression_toolkit/core/common/mixed_precision/kpi_tools/kpi_aggregation_methods.py
  model_compression_toolkit/core/common/mixed_precision/kpi_tools/kpi_data.py
  model_compression_toolkit/core/common/mixed_precision/kpi_tools/kpi_functions_mapping.py
  model_compression_toolkit/core/common/mixed_precision/kpi_tools/kpi_methods.py
  model_compression_toolkit/core/common/mixed_precision/mixed_precision_search_facade.py
  model_compression_toolkit/core/common/mixed_precision/mixed_precision_search_manager.py
  model_compression_toolkit/core/common/mixed_precision/search_methods/linear_programming.py
  model_compression_toolkit/core/keras/kpi_data_facade.py
  model_compression_toolkit/core/keras/quantization_facade.py
  model_compression_toolkit/core/pytorch/kpi_data_facade.py
  model_compression_toolkit/core/pytorch/quantization_facade.py
  model_compression_toolkit/core/runner.py
  model_compression_toolkit/gptq/keras/quantization_facade.py
  model_compression_toolkit/gptq/pytorch/quantization_facade.py
  model_compression_toolkit/ptq/keras/quantization_facade.py
  model_compression_toolkit/ptq/pytorch/quantization_facade.py
  model_compression_toolkit/qat/keras/quantization_facade.py
  model_compression_toolkit/qat/pytorch/quantization_facade.py
  tests/keras_tests/feature_networks_tests/feature_networks/mixed_precision_tests.py
  tests/keras_tests/feature_networks_tests/feature_networks/reused_layer_mixed_precision_test.py
  tests/keras_tests/feature_networks_tests/feature_networks/weights_mixed_precision_tests.py
  tests/keras_tests/function_tests/test_lp_search_bitwidth.py
Labels: keras, pytorch, size/m

#310 Fix in total KPI method
  model_compression_toolkit/core/common/mixed_precision/kpi_tools/kpi_methods.py
Labels: size/s

#312 Final KPI recording
  model_compression_toolkit/core/common/mixed_precision/kpi_tools/kpi.py
  model_compression_toolkit/core/common/mixed_precision/kpi_tools/kpi_aggregation_methods.py
  model_compression_toolkit/core/common/user_info.py
  model_compression_toolkit/core/runner.py
  tests/keras_tests/feature_networks_tests/feature_networks/mixed_precision_tests.py
  tests/keras_tests/feature_networks_tests/feature_networks/weights_mixed_precision_tests.py
Labels: common, size/m

#308 update QAT and add export API
  docsrc/source/api/experimental_api_docs/index.rst
  docsrc/source/api/experimental_api_docs/methods/keras_quantization_aware_training_export.rst
  docsrc/source/api/experimental_api_docs/methods/keras_quantization_aware_training_init.rst
  docsrc/source/index.rst
  model_compression_toolkit/__init__.py
  model_compression_toolkit/core/common/defaultdict.py
  model_compression_toolkit/core/common/framework_info.py
  model_compression_toolkit/qat/keras/model_builder.py
  model_compression_toolkit/qat/keras/quantization_facade.py
  tests/keras_tests/feature_networks_tests/feature_networks/qat_test.py
  tests/keras_tests/feature_networks_tests/test_features_runner.py
Labels: common, size/m
